
</br></br></br><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Customer Report</td></tr><tr><td align='center'>Total number of customers till date</td><td align='center'>64</td></tr></table></br></br></br><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Stock report</td></tr><tr><td align='center'>Fantasy</td><td align='center'>-15</td></tr><tr><td align='center'>Adventure</td><td align='center'>11</td></tr></table></br></br></br><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>27.625000000000004</td></tr></table><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>13.007407407407406</td></tr></table><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>50.5</td></tr></table><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>18.7</td></tr></table><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>6.7727272727272725</td></tr></table><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>7.45</td></tr></table><table align='center' border='2' style='border:2px solid blue;'><tr><td align='center' colspan='2'>Sales Report</td></tr><tr><td align='center'>Sales average till date</td><td align='center'>47.3625</td></tr></table><form action='screen1.php' method='post' align='center'><input type='submit' name='cancel' value='EXIT 3-B.com[Admin]'></form><html>
<head>
<title>Reports</title>
</head>
<body>
	
</body>
</html>

